version: "3.8"

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GITHUB_PAT: ${GITHUB_PAT}
      REPO_URL: https://github.com/jamescoller/inventory_management
      RUNNER_LABELS: inventory-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    container_name: github-runner
