services:
  web:
    build: .
    command: ["/app/entrypoint.sh"]
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /volume1/docker/inventory_management:/app
      - static_volume:/app/staticfiles  # ✅ Match STATIC_ROOT!
    expose:
      - "8000"
    environment:
      - DEBUG=0
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - static_volume:/static  # ✅ Match nginx.conf alias!
      - /volume1/docker/inventory_management/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
