services:
  web:
    build: .
    command: ["/app/entrypoint.sh"]
    restart: always
    volumes:
      - .:/app
      - static_volume:/static/
    expose:
      - "8000"  # only expose internally, nginx will access it
    environment:
      - DEBUG=0

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - static_volume:/static/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume: