# Generated by Django 4.2.20 on 2025-05-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_filament_dry_temp_ideal_degc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="object_id",
        ),
    ]
