# Generated by Django 4.2.20 on 2025-05-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='content_type',
        ),
    ]
