# Generated by Django 4.2.20 on 2025-05-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='upc',
        ),
    ]
