# Generated by Django 4.2.20 on 2025-05-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_remove_inventoryitem_upc"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="default_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "new"),
                    (2, "in use"),
                    (3, "drying"),
                    (4, "stored"),
                    (5, "depleted"),
                ],
                default=1,
                help_text="Default status to apply to items moved to this location.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
