# Generated by Django 4.2.20 on 2025-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_location_default_status_alter_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
