# Generated by Django 4.2.20 on 2025-05-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0011_alter_ams_options_alter_dryer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="Product Type",
            ),
        ),
    ]
