# Generated by Django 4.2.20 on 2025-05-25 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_product_polymorphic_ctype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="user",
        ),
    ]
