# Generated by Django 4.2.20 on 2025-06-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_remove_inventoryitem_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "mfr",
                    models.CharField(blank=True, default="Bambu Lab", max_length=100),
                ),
                ("print_temp_min_degC", models.IntegerField(blank=True, null=True)),
                ("print_temp_max_degC", models.IntegerField(blank=True, null=True)),
                ("print_temp_ideal_degC", models.IntegerField(blank=True, null=True)),
                ("dry_temp_min_degC", models.IntegerField(blank=True, null=True)),
                ("dry_temp_max_degC", models.IntegerField(blank=True, null=True)),
                ("dry_temp_ideal_degC", models.IntegerField(blank=True, null=True)),
                ("dry_time_hrs", models.IntegerField(blank=True, null=True)),
                ("ams_capable", models.BooleanField(default=True)),
                ("drying_required", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name="printer",
            old_name="print_volume_mm3",
            new_name="print_volume_m3",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="dry_temp_ideal_degC",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="dry_temp_max_degC",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="dry_temp_min_degC",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="dry_time_hrs",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="print_temp_ideal_degC",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="print_temp_max_degC",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="print_temp_min_degC",
        ),
        migrations.RemoveField(
            model_name="hardware",
            name="usage",
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="ams",
            name="drying",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="filament",
            name="has_spool",
            field=models.BooleanField(
                default=False, help_text="Does the filament come on a spool?"
            ),
        ),
        migrations.AddField(
            model_name="filament",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight of the filament in kilograms",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hardware",
            name="qty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="date_sold",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="depleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="in_use",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="percent_remaining",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=100, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="location",
            name="is_printer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="filament",
            name="color",
            field=models.CharField(
                help_text="Human-readable color name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="filament",
            name="hex_code",
            field=models.CharField(
                help_text="3 or 6 character hexadecimal color code string", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="kind",
            field=models.IntegerField(
                choices=[
                    (1, "Accessory"),
                    (2, "Spare Part"),
                    (3, "Hardware"),
                    (4, "Raw Material"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="serial_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="shipment",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "new"),
                    (2, "in use"),
                    (3, "drying"),
                    (4, "stored"),
                    (5, "depleted"),
                    (6, "sold"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="default_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "new"),
                    (2, "in use"),
                    (3, "drying"),
                    (4, "stored"),
                    (5, "depleted"),
                    (6, "sold"),
                ],
                help_text="Default status to apply to items moved to this location.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A shorter ID code within Bambu Lab",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="upc",
            field=models.CharField(
                help_text="12 or 13 digit barcode number", max_length=50, unique=True
            ),
        ),
    ]
