# Generated by Django 4.2.20 on 2025-06-24 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_material_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filament",
            name="new_matl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.material",
            ),
        ),
    ]
