# Generated by Django 4.2.20 on 2025-06-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_filament_new_matl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filament",
            name="material",
        ),
        migrations.RemoveField(
            model_name="filament",
            name="material_type",
        ),
    ]
