# Generated by Django 4.2.20 on 2025-06-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_filament_material_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filament",
            old_name="new_matl",
            new_name="material",
        ),
    ]
