# Generated by Django 4.2.20 on 2025-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_rename_new_matl_filament_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="filament",
            name="color_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("ORANGE", "Orange"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                    ("BLUE", "Blue"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("BROWN", "Brown"),
                    ("BLACK", "Black"),
                    ("GRAY", "Gray"),
                    ("WHITE", "White"),
                ],
                help_text="Automatically determined from hex code",
                max_length=20,
            ),
        ),
    ]
