# Generated by Django 4.2.20 on 2025-06-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_filament_color_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filament",
            name="color",
            field=models.CharField(
                blank=True, help_text="Human-readable color name", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="filament",
            name="color_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("ORANGE", "Orange"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                    ("BLUE", "Blue"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("BROWN", "Brown"),
                    ("BLACK", "Black"),
                    ("GRAY", "Gray"),
                    ("WHITE", "White"),
                    ("TRANSLUCENT", "Translucent"),
                ],
                help_text="Automatically determined from hex code",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="filament",
            name="hex_code",
            field=models.CharField(
                blank=True,
                help_text="3 or 6 character hexadecimal color code string",
                max_length=7,
            ),
        ),
    ]
