# Generated by Django 6.0.5 on 2026-05-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_material_type_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["name", "material_type"]},
        ),
    ]
