# Generated by Django 6.0.5 on 2026-05-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_alter_material_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="budget_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="material",
            name="easy_to_print",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="flexible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="food_safe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="heat_resistant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="high_strength",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="impact_resistant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="requires_enclosure",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="material",
            name="uv_resistant",
            field=models.BooleanField(default=False),
        ),
    ]
