# Generated by Django 6.0.5 on 2026-06-02 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_material_budget_friendly_material_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="kind",
            field=models.CharField(
                choices=[
                    ("rack", "Receiving Rack"),
                    ("shelf", "Shelf"),
                    ("dry_storage", "Dry Storage"),
                    ("ams", "AMS Unit"),
                    ("ams_slot", "AMS Slot"),
                    ("dryer", "Dryer"),
                    ("dryer_slot", "Dryer Slot"),
                    ("printer", "Printer"),
                ],
                default="shelf",
                help_text="Structural type of this location.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent container (shelf->rack, slot->unit).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="inventory.location",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="slot_index",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Slot number within an AMS/dryer (1-4).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="The physical AMS/dryer unit this slot belongs to, if tracked.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_locations",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "new"),
                    (2, "in use"),
                    (3, "drying"),
                    (4, "stored"),
                    (5, "depleted"),
                    (6, "sold"),
                    (7, "unknown"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="default_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "new"),
                    (2, "in use"),
                    (3, "drying"),
                    (4, "stored"),
                    (5, "depleted"),
                    (6, "sold"),
                    (7, "unknown"),
                ],
                help_text="Default status to apply to items moved to this location.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("finalized", "Finalized"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("visited", "Location visited"),
                            ("scanned_present", "Scanned present"),
                            ("moved_in", "Moved in"),
                            ("revived", "Revived"),
                            ("flagged_unknown", "Flagged unknown"),
                            ("closed", "Location closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inventory.auditsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="auditsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("state",),
                name="unique_active_audit_session",
            ),
        ),
    ]
