# Generated by Django 6.0.5 on 2026-06-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_backfill_location_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("visited", "Location visited"),
                    ("scanned_present", "Scanned present"),
                    ("moved_in", "Moved in"),
                    ("revived", "Revived"),
                    ("flagged_unknown", "Flagged unknown"),
                    ("closed", "Location closed"),
                    ("added", "Added during audit"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditUnknownScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("upc", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.location",
                    ),
                ),
                (
                    "resolved_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unknown_scans",
                        to="inventory.auditsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dismissed", False), ("resolved", False)),
                        fields=("session", "upc", "location"),
                        name="unique_open_unknown_scan",
                    )
                ],
            },
        ),
    ]
