# Generated by Django 6.0.5 on 2026-06-09 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_audit_unknown_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="NozzleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nozzle_diameter_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "nozzle_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. hardened steel, brass.",
                        max_length=50,
                    ),
                ),
                ("hotend_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "printer",
                    models.OneToOneField(
                        help_text="The printer InventoryItem this nozzle is installed on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzle_config",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nozzle Configuration",
                "verbose_name_plural": "Nozzle Configurations",
            },
        ),
        migrations.CreateModel(
            name="MaintenanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Fault"),
                            (2, "Repair"),
                            (3, "Part replacement"),
                            (4, "Lubricate"),
                            (5, "Clean"),
                            (6, "Calibrate"),
                            (7, "Hotend / nozzle swap"),
                            (8, "Firmware update"),
                            (9, "Inspect"),
                            (10, "Other"),
                        ],
                        default=9,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Info"),
                            (2, "Minor"),
                            (3, "Major"),
                            (4, "Critical"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True, default="")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "downtime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "hms_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bambu HMS error code (populated by the MQTT consumer later).",
                        max_length=32,
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=True,
                        help_text="False = an open fault still needing attention.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Hardware product consumed (for part replacements / hotend swaps).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_uses",
                        to="inventory.hardware",
                    ),
                ),
                (
                    "part_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The tracked InventoryItem consumed as the part, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_as",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The machine (printer/AMS/dryer) this event concerns.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_events",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Event",
                "verbose_name_plural": "Maintenance Events",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["unit", "kind"], name="inventory_m_unit_id_f351bc_idx"
                    ),
                    models.Index(
                        fields=["occurred_at"], name="inventory_m_occurre_fd8640_idx"
                    ),
                ],
            },
        ),
    ]
