# Generated by Django 6.0.5 on 2026-06-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_audit_unknown_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="build_plate_compat",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="material",
            name="hot_end_compat",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
