# Generated by Django 6.0.5 on 2026-06-09 05:21

from django.db import migrations, models


def seed_slot_capacities(apps, schema_editor):
    """Backfill capacity=1 for existing single-occupancy slot rows.

    Non-destructive: only fills NULLs on ams_slot/dryer_slot. All other
    assignable kinds stay NULL (unlimited). New rows get the same default via
    ``Location.save``. Slot kind strings are hard-coded here (migrations must not
    import live model class attributes) and match ``Location.Kind``.
    """
    Location = apps.get_model("inventory", "Location")
    Location.objects.filter(
        kind__in=("ams_slot", "dryer_slot"), capacity__isnull=True
    ).update(capacity=1)


def noop_reverse(apps, schema_editor):
    # Reversing simply drops the column (handled by RemoveField); the data
    # backfill has nothing to undo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_audit_unknown_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="capacity",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Maximum number of active items this location can hold. Blank = unlimited. AMS/dryer slots default to 1.",
                null=True,
            ),
        ),
        migrations.RunPython(seed_slot_capacities, noop_reverse),
    ]
