# Generated by Django 6.0.5 on 2026-06-09 17:27

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_material_build_plate_compat_material_hot_end_compat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalInventoryItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("shipment", models.CharField(blank=True, default="", max_length=100)),
                ("date_added", models.DateTimeField(blank=True, editable=False)),
                (
                    "serial_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_modified", models.DateTimeField(blank=True, editable=False)),
                ("date_depleted", models.DateTimeField(blank=True, null=True)),
                ("date_sold", models.DateTimeField(blank=True, null=True)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "percent_remaining",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "new"),
                            (2, "in use"),
                            (3, "drying"),
                            (4, "stored"),
                            (5, "depleted"),
                            (6, "sold"),
                            (7, "unknown"),
                        ],
                        default=1,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Inventory Item",
                "verbose_name_plural": "historical Inventory Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
