# Generated by Django 6.0.5 on 2026-06-09 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_nozzleconfig_maintenanceevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="gcode / 3mf file name.",
                        max_length=255,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_s",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Print duration in seconds. Derived from start/end if blank.",
                        null=True,
                    ),
                ),
                (
                    "result",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "success"),
                            (2, "failed"),
                            (3, "cancelled"),
                            (4, "partial"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "source",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "manual"), (2, "mqtt")], default=1
                    ),
                ),
                (
                    "telemetry_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bambu subtask id — dedup key for MQTT auto-ingest.",
                        max_length=64,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False,
                        help_text="True once consumption has been applied to the referenced spools.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "printer",
                    models.ForeignKey(
                        help_text="The printer InventoryItem this job ran on.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_jobs",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Job",
                "verbose_name_plural": "Print Jobs",
                "ordering": ["-started_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrintJobFilament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grams_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "percent_used",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "ams_slot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which slot the spool drew from, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_uses",
                        to="inventory.location",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_uses",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filaments",
                        to="inventory.printjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Job Filament",
                "verbose_name_plural": "Print Job Filaments",
            },
        ),
    ]
