# Generated by Django 6.0.5 on 2026-06-09 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_printjob_printjobfilament"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Supplier order / confirmation number.",
                        max_length=120,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Draft"),
                            (2, "Ordered"),
                            (3, "Partially received"),
                            (4, "Received"),
                            (5, "Cancelled"),
                        ],
                        default=1,
                    ),
                ),
                ("ordered_at", models.DateField(blank=True, null=True)),
                ("expected_at", models.DateField(blank=True, null=True)),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "account_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer/account number.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-unit price actually paid (distinct from catalog price).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-unit price actually paid (distinct from catalog price).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot description for odd / off-catalog items.",
                        max_length=255,
                    ),
                ),
                ("qty_ordered", models.PositiveIntegerField(default=1)),
                ("qty_received", models.PositiveIntegerField(default=0)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="Per-unit price paid.", max_digits=8
                    ),
                ),
                (
                    "track_individually",
                    models.BooleanField(
                        default=True,
                        help_text="True = mint a tracked InventoryItem per received unit. False = cost-only consumable (e.g. screws); no items are created.",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_lines",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Line",
                "verbose_name_plural": "Purchase Order Lines",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="historicalinventoryitem",
            name="source_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The purchase-order line this item was received against.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="source_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The purchase-order line this item was received against.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_items",
                to="inventory.purchaseorderline",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Receipt/confirmation file. Inert until media storage is configured (MEDIA_ROOT/MEDIA_URL + nginx alias + media volume).",
                        null=True,
                        upload_to="receipts/%Y/%m/",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="inventory.purchaseorder",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Receipt",
                "verbose_name_plural": "Purchase Receipts",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_received", models.PositiveIntegerField()),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="inventory.purchaseorderline",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.purchasereceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Receipt Line",
                "verbose_name_plural": "Purchase Receipt Lines",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="inventory.supplier",
            ),
        ),
    ]
