# Generated by Django 6.0.5 on 2026-06-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_purchaseorder_supplier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrinterDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "access_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("model_name", models.CharField(blank=True, default="", max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional curated link to the machine's InventoryItem (16.3).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printer_device",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrinterState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gcode_state",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("mc_percent", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("layer_num", models.PositiveIntegerField(blank=True, null=True)),
                ("total_layers", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "nozzle_temp",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "nozzle_target",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "bed_temp",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "bed_target",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("remaining_min", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "subtask_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("task_id", models.CharField(blank=True, default="", max_length=64)),
                ("hms_codes", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="inventory.printerdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AMSUnitState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ams_index", models.PositiveSmallIntegerField()),
                ("humidity", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "humidity_raw",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "temp",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("dry_time", models.PositiveIntegerField(blank=True, null=True)),
                ("dry_duration", models.IntegerField(blank=True, null=True)),
                ("dry_temperature", models.IntegerField(blank=True, null=True)),
                (
                    "dry_filament",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ams_units",
                        to="inventory.printerdevice",
                    ),
                ),
            ],
            options={
                "unique_together": {("device", "ams_index")},
            },
        ),
        migrations.CreateModel(
            name="AMSChannelState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ams_index", models.PositiveSmallIntegerField()),
                ("tray_index", models.PositiveSmallIntegerField()),
                ("tray_uuid", models.CharField(blank=True, default="", max_length=64)),
                (
                    "tray_info_idx",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("tray_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "tray_sub_brands",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("color_hex", models.CharField(blank=True, default="", max_length=8)),
                ("remain_pct", models.SmallIntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ams_channels",
                        to="inventory.printerdevice",
                    ),
                ),
            ],
            options={
                "unique_together": {("device", "ams_index", "tray_index")},
            },
        ),
        migrations.CreateModel(
            name="TelemetrySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField()),
                (
                    "gcode_state",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("mc_percent", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "nozzle_temp",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "bed_temp",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("remaining_min", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="inventory.printerdevice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device", "ts"], name="inventory_t_device__5a21e2_idx"
                    )
                ],
            },
        ),
    ]
