# Generated by Django 6.0.5 on 2026-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_printerdevice_printerstate_amsunitstate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filament",
            name="manufacturer",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Brand of this spool (e.g. Bambu Lab, Polymaker)",
                max_length=100,
            ),
        ),
    ]
