# Generated by Django 6.0.5 on 2026-06-12 04:13

from django.db import migrations, models

CATEGORY_BY_BASE = {
    "PLA": "everyday",
    "PETG": "everyday",
    "ABS": "everyday",
    "ASA": "everyday",
    "PC": "engineering",
    "PA6": "engineering",
    "PAHT": "engineering",
    "PET": "engineering",
    "PPS": "engineering",
    "TPU": "flexible",
    "PVA": "support",
    "Support": "support",
}


def backfill(apps, schema_editor):
    Material = apps.get_model("inventory", "Material")
    for m in Material.objects.all():
        m.drying_need = "required" if m.drying_required else "not_needed"
        m.category = CATEGORY_BY_BASE.get(m.name, "everyday")
        m.save(update_fields=["drying_need", "category"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_backfill_filament_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.CharField(
                choices=[
                    ("everyday", "Everyday"),
                    ("engineering", "Engineering"),
                    ("flexible", "Flexible"),
                    ("support", "Support"),
                ],
                default="everyday",
                help_text="Drives guide grouping; SUPPORT materials are excluded from the picker.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="drying_need",
            field=models.CharField(
                choices=[
                    ("not_needed", "Not needed"),
                    ("recommended", "Recommended"),
                    ("required", "Required"),
                ],
                default="required",
                help_text="Whether drying is required, recommended, or not needed before printing.",
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill, noop),
        migrations.RemoveField(
            model_name="material",
            name="drying_required",
        ),
        migrations.RemoveField(
            model_name="material",
            name="food_safe",
        ),
    ]
