# Generated by Django 6.0.5 on 2026-06-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_material_guide_drying_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="filament",
            name="hex_code_2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Second hex for two-tone / gradient spools; renders a gradient swatch.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="filament",
            name="color_family",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RED", "Red"),
                    ("ORANGE", "Orange"),
                    ("YELLOW", "Yellow"),
                    ("GREEN", "Green"),
                    ("BLUE", "Blue"),
                    ("PURPLE", "Purple"),
                    ("PINK", "Pink"),
                    ("BROWN", "Brown"),
                    ("BLACK", "Black"),
                    ("GRAY", "Gray"),
                    ("WHITE", "White"),
                    ("TRANSLUCENT", "Translucent"),
                    ("GRADIENT", "Gradient"),
                ],
                help_text="Automatically determined from hex code",
                max_length=20,
            ),
        ),
    ]
