# Generated by Django 6.0.5 on 2026-06-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_filament_hex_code_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="store_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manufacturer store product slug (Bambu), e.g. 'pla-matte'. Blank falls back to a store search link.",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="FilamentColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        default="Bambu Lab",
                        help_text="Brand of this color (e.g. Bambu Lab, Polymaker)",
                        max_length=100,
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        help_text="Base polymer, e.g. 'PLA'", max_length=100
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Subtype, e.g. 'Matte'",
                        max_length=50,
                    ),
                ),
                ("color_name", models.CharField(max_length=80)),
                (
                    "hex_code",
                    models.CharField(help_text="#RRGGBB; gradient start", max_length=9),
                ),
                (
                    "hex_code_2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Set => gradient end color",
                        max_length=9,
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=120)),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved spec row; supplies header specs + store_slug.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_colors",
                        to="inventory.material",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "manufacturer",
                    "material_name",
                    "material_type",
                    "color_name",
                ],
                "unique_together": {
                    ("manufacturer", "material_name", "material_type", "color_name")
                },
            },
        ),
    ]
