# Generated by Django 4.2.20 on 2025-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_location_remove_inventoryitem_name_inventoryitem_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='shipment',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
