# Generated by Django 4.2.20 on 2025-04-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_shipment_alter_inventoryitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
    ]
