# Generated by Django 4.2.20 on 2025-04-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='date_depleated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'in use'), (3, 'drying'), (4, 'stored'), (5, 'depleted')], default=1),
        ),
    ]
