name: Deploy to Synology NAS

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run NAS deployment script
        run: bash inventory_management/scripts/deploy.sh
