name: Deploy to Synology NAS

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run NAS deployment script 
        run: bash /mnt/inventory_management/scripts/deploy.sh

