name: Deploy to Synology NAS

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name:
          Debug: Print current directory
        run: |
          echo "Current dir: $(pwd)"

      - name:
          Debug: List files in current directory
        run: |
          ls -al

      - name:
          Debug: Recursively list all files
        run: |
          ls -alR

      - name: Run deployment script
        run: bash scripts/deploy.sh
